v: 2.6.0
overrideConfig: false
ie:
  - DS_Store
  - less
  - scss
id:
  - scss
  - .svn
  - .sass-cache
  - fonts
  - icons
cleanPublic: 'true'
patternStates:
  - inprogress
  - inreview
  - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: ../../dist/public/
sourceDir: ../../source/
defaultPattern: all
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
  - hay
lineageMatch: >-
  {%([ ]+)?include(
  |\()[&quot;\&#039;]([A-Za-z0-9-_]+)[&quot;\&#039;](\))?(.*)%}
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: false
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
plugins:
  faker:
    enabled: true
    locale: en_US
  twigNamespaces:
    enabled: true
    namespaces:
      base:
        paths:
          - ../../source/_patterns/00-base
          - ../../source/_patterns/00-base/10-spacing
          - ../../source/_patterns/00-base/breakpoints
          - ../../source/_patterns/00-base/utilities/borders
          - ../../source/_patterns/00-base/15-typography/text
          - ../../source/_patterns/00-base/15-typography/fonts
          - ../../source/_patterns/00-base/15-typography/lists
          - ../../source/_patterns/00-base/15-typography/headings
          - ../../source/_patterns/00-base/animations/01-transitions
      atoms:
        paths:
          - ../../source/_patterns/01-atoms
          - ../../source/_patterns/01-atoms/grid
          - ../../source/_patterns/01-atoms/tabs
          - ../../source/_patterns/01-atoms/icons
          - ../../source/_patterns/01-atoms/image
          - ../../source/_patterns/01-atoms/pager
          - ../../source/_patterns/01-atoms/views
          - ../../source/_patterns/01-atoms/button
          - ../../source/_patterns/01-atoms/facets
          - ../../source/_patterns/01-atoms/images
          - ../../source/_patterns/01-atoms/search
          - ../../source/_patterns/01-atoms/buttons
          - ../../source/_patterns/01-atoms/list-item
          - ../../source/_patterns/01-atoms/long-text
          - ../../source/_patterns/01-atoms/breadcrumb
          - ../../source/_patterns/01-atoms/input-email
          - ../../source/_patterns/01-atoms/menu-account
          - ../../source/_patterns/01-atoms/node-metadata
          - ../../source/_patterns/01-atoms/voting-widget
          - ../../source/_patterns/01-atoms/input-password
          - ../../source/_patterns/01-atoms/list-view-list
          - ../../source/_patterns/01-atoms/input-textfield
          - ../../source/_patterns/01-atoms/user-profile-extras
          - ../../source/_patterns/01-atoms/profile-picture-only
          - ../../source/_patterns/01-atoms/views-field-metadata
          - ../../source/_patterns/01-atoms/account-request-select
          - ../../source/_patterns/01-atoms/organizations-i-manage
          - ../../source/_patterns/01-atoms/product-areas-i-support
          - ../../source/_patterns/01-atoms/account-request-textarea
          - ../../source/_patterns/01-atoms/user-view-comment-author
          - ../../source/_patterns/01-atoms/user-view-content-author
          - ../../source/_patterns/01-atoms/user-view-member-directory
      molecules:
        paths:
          - ../../source/_patterns/02-molecules
          - ../../source/_patterns/02-molecules/branding
          - ../../source/_patterns/02-molecules/comments
          - ../../source/_patterns/02-molecules/main-menu
          - ../../source/_patterns/02-molecules/account-menu
      organisms:
        paths:
          - ../../source/_patterns/03-organisms
          - ../../source/_patterns/03-organisms/blocks/posted-by
          - ../../source/_patterns/03-organisms/site/site-footer
          - ../../source/_patterns/03-organisms/site/site-header
          - ../../source/_patterns/03-organisms/blocks/product-manager
          - ../../source/_patterns/03-organisms/blocks/idea-more-details
          - ../../source/_patterns/03-organisms/grids/caption-grid-block
          - ../../source/_patterns/03-organisms/blocks/manage-subscriptions
      templates:
        paths:
          - ../../source/_patterns/04-templates
          - ../../source/_patterns/04-templates/00-site
          - ../../source/_patterns/04-templates/content-types
      pages:
        paths:
          - ../../source/_patterns/05-pages
